services:
    solidjeuh.boardmagic.listener:
        class: solidjeuh\boardmagic\event\listener
        arguments:
            - '@config'
            - '@template'
        tags:
            - { name: event.listener }
parameters:
    debug.load_time: true
    debug.sql_explain: true
    debug.memory: true
    debug.show_errors: true
    debug.exceptions: true