services:
    solidjeuh.boardmagic.listener:
        class: solidjeuh\boardmagic\event\listener
        arguments:
            - '@config'
            - '@template'
        tags:
            - { name: event.listener }
